if(NOT DEFINED PLATFORM_NAME OR PLATFORM_NAME STREQUAL "")
  if(APPLE)
    set(PLATFORM_NAME "macos")
  elseif(WIN32)
    set(PLATFORM_NAME "window_x86_64")
  else()
    set(PLATFORM_NAME "linux_x86_64")
  endif()
endif()

message("PLATFORM_NAME:${PLATFORM_NAME}")

set(macos_platform false)
set(linux_x86_64_platform false)
set(window_x86_64_platform false)

if(PLATFORM_NAME STREQUAL "macos")
  set(macos_platform true)
  add_definitions(-DMACOS_PLATFORM)
elseif(PLATFORM_NAME STREQUAL "linux_x86_64")
  set(linux_x86_64_platform true)
  add_definitions(-DLINUX_X86_64)
elseif(PLATFORM_NAME STREQUAL "window_x86_64")
  set(window_x86_64_platform true)
  add_definitions(-DWINDOW_X86_64)
else()
  message(WARNING "Unknown PLATFORM_NAME='${PLATFORM_NAME}'. No platform macro is defined.")
endif()

set(BUILD_ARCH_X86 0)
if(linux_x86_64_platform OR macos_platform OR window_x86_64_platform)
  set(BUILD_ARCH_X86 1)
endif()
add_definitions(-DBUILD_ARCH_X86=${BUILD_ARCH_X86})
